test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -106,7 +106,7 @@ jobs:
 
                 echo "####docker-build."
                 # Composer 依存関係をインストール
-                sudo docker-compose exec -w /var/www php bash -c "composer install" || { echo "Composer install failed"; exit 1; }
+                sudo docker-compose exec  php bash -c "composer install" || { echo "Composer install failed"; exit 1; }
 
                 # MySQLコンテナを再起動
                 docker-compose restart mysql || { echo "MySQL restart failed"; exit 1; }
@@ -127,12 +127,12 @@ jobs:
                 echo "MySQL is ready."
 
                 # データベースマイグレーションとシーディングを実行
-                sudo docker-compose exec -w /var/www php bash -c "php artisan migrate --force" || { echo "Migration failed"; exit 1; }
-                sudo docker-compose exec -w /var/www php bash -c "php artisan db:seed --force" || { echo "Seeding failed"; exit 1; }
+                sudo docker-compose exec php bash -c "php artisan migrate --force" || { echo "Migration failed"; exit 1; }
+                sudo docker-compose exec php bash -c "php artisan db:seed --force" || { echo "Seeding failed"; exit 1; }
 
                 # NPM依存関係をインストールしてビルド
-                docker-compose exec -w /var/www php bash -c "npm install" || { echo "NPM install failed"; exit 1; }
-                docker-compose exec -w /var/www php bash -c "npm run build" || { echo "NPM build failed"; exit 1; }
+                docker-compose exec php bash -c "npm install" || { echo "NPM install failed"; exit 1; }
+                docker-compose exec php bash -c "npm run build" || { echo "NPM build failed"; exit 1; }
 
                 # アプリケーションを PM2 で再起動
                 pm2 restart all || { echo "PM2 restart failed"; exit 0; }
